//! Generates the tier-3 custom-effect registration table from `src/custom/**/*.rs` so adding a
//! custom card never requires editing source: drop a file named after the card id (any
//! subdirectory) that exports `EFFECT`, and it is registered. The mirror of
//! `tricerules-cards/build.rs`, which does the same for RON card data.
//!
//! The file stem *is* the card id (the registry's `id == slugify(name)` convention reused as a
//! filesystem convention), so the binding is declared exactly once — in the card's RON
//! `custom_effect` — and nowhere in Rust. Paths are sorted for deterministic output.
//!
//! Skipped: `mod.rs`, and anything under a directory named `support` (shared helper modules that
//! are not themselves card effects).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Directory name reserved for shared helper modules, which `custom/mod.rs` declares itself.
const SUPPORT_DIR: &str = "support";

fn collect_effect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("read custom dir") {
        let path = entry.expect("read custom dir entry").path();
        if path.is_dir() {
            if path.file_name().is_some_and(|n| n == SUPPORT_DIR) {
                continue;
            }
            collect_effect_files(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs")
            && path.file_name().is_some_and(|n| n != "mod.rs")
        {
            out.push(path);
        }
    }
}

/// Rust keywords (2015 + 2018 strict and reserved) that a card id could collide with. A stem here
/// cannot be emitted as a module name. No real card id hits this, but the failure is worth naming.
const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
    "where", "while", "abstract", "async", "await", "become", "box", "do", "final", "macro",
    "override", "priv", "try", "typeof", "unsized", "virtual", "yield",
];

/// The generated module name is the stem verbatim, so the stem must be a legal Rust identifier.
/// Registry ids are `slugify(name)` — lowercase ASCII, digits and underscores — so this only ever
/// fires on a leading digit or a keyword collision. If a real card ever needs it, the escape hatch
/// is to sanitize the *module identifier* while leaving the key string alone: the emitted table
/// already carries them as separate columns. Keeping them equal is what makes it greppable.
fn reject_illegal_stem(stem: &str, path: &Path) {
    let legal_chars = !stem.is_empty()
        && stem
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        && !stem.starts_with(|c: char| c.is_ascii_digit());
    if !legal_chars || RUST_KEYWORDS.contains(&stem) {
        panic!(
            "custom effect file {} has stem `{stem}`, which is not a legal Rust module name. \
             The stem is the card id, so rename the file to the card's registry id (lowercase, \
             underscores, no leading digit).",
            path.display()
        );
    }
}

fn main() {
    // Directory-level: re-runs on file adds, removes, and edits anywhere under src/custom/.
    println!("cargo:rerun-if-changed=src/custom");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let mut files = Vec::new();
    collect_effect_files(&manifest_dir.join("src").join("custom"), &mut files);
    files.sort();

    // Keyed by stem so a duplicate is a build failure rather than two impls silently claiming one
    // card id — the collision half of the "custom_effect key uniqueness is never validated"
    // finding, caught before the crate compiles. Custom effects are 1:1 with card ids, exactly
    // like RON data cards: two cards wanting one algorithm is the signal to widen a primitive.
    let mut by_stem: BTreeMap<String, PathBuf> = BTreeMap::new();
    for path in files {
        let stem = path
            .file_stem()
            .expect("effect file stem")
            .to_str()
            .expect("utf-8 file stem")
            .to_string();
        reject_illegal_stem(&stem, &path);
        if let Some(first) = by_stem.get(&stem) {
            panic!(
                "two custom effect files claim card id `{stem}`: {} and {}. \
                 Custom effects are 1:1 with card ids.",
                first.display(),
                path.display()
            );
        }
        by_stem.insert(stem, path);
    }

    let mut generated = String::from(
        "// Generated by build.rs from `src/custom/**/*.rs`; never edited by hand.\n\
         // The file stem is the card id. Absolute `#[path]` is required: a bare `mod foo;` inside\n\
         // an `include!`d file resolves relative to OUT_DIR, not the include site.\n",
    );
    let mut table = String::from(
        "/// Every registered tier-3 effect, as (card id, impl). Built into a map by `lookup`.\n\
         const EFFECT_IMPLS: &[(&str, &'static dyn CardEffect)] = &[\n",
    );
    for (stem, path) in &by_stem {
        let abs = path.to_str().expect("utf-8 path").replace('\\', "/");
        generated.push_str(&format!("#[path = \"{abs}\"]\npub(crate) mod {stem};\n"));
        table.push_str(&format!("    (\"{stem}\", {stem}::EFFECT),\n"));
    }
    table.push_str("];\n");
    generated.push_str(&table);

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("custom_effects.rs");
    fs::write(&out_path, generated).expect("write custom_effects.rs");
}
