//! Generates the embedded card list from `data/**/*.ron` so adding a card never
//! requires editing source: drop a RON file in `data/` (any subdirectory) and it
//! is compiled in. Paths are sorted for deterministic output.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn collect_ron_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("read data dir") {
        let path = entry.expect("read data dir entry").path();
        if path.is_dir() {
            collect_ron_files(&path, out);
        } else if path.extension().is_some_and(|e| e == "ron") {
            out.push(path);
        }
    }
}

fn main() {
    // Directory-level: re-runs on file adds, removes, and edits anywhere under data/.
    println!("cargo:rerun-if-changed=data");
    println!("cargo:rerun-if-changed=presentation/oracle_fingerprints.tsv");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let mut files = Vec::new();
    collect_ron_files(&manifest_dir.join("data"), &mut files);
    files.sort();

    // Token RON (anything under `data/tokens/`) deserializes into TokenDefinition, not
    // CardDefinition, so it is emitted into a separate array the registry loads distinctly.
    let mut generated = String::new();
    let mut card_list = String::from(
        "/// Ron snippets compiled into the binary (hybrid model: data-first).\n\
         /// Generated by build.rs from `data/**/*.ron` (excluding `data/tokens/`); never edited by hand.\n\
         const EMBEDDED_RON_CHUNKS: &[&str] = &[\n",
    );
    let mut token_list = String::from(
        "/// Token RON snippets from `data/tokens/**/*.ron`; loaded as TokenDefinition.\n\
         const EMBEDDED_TOKEN_CHUNKS: &[&str] = &[\n",
    );
    for file in &files {
        let rel = file
            .strip_prefix(&manifest_dir)
            .expect("data file under manifest dir")
            .to_str()
            .expect("utf-8 path")
            .replace('\\', "/");
        let line =
            format!("    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\")),\n");
        if rel.starts_with("data/tokens/") {
            token_list.push_str(&line);
        } else {
            card_list.push_str(&line);
        }
    }
    card_list.push_str("];\n");
    token_list.push_str("];\n");
    generated.push_str(&card_list);
    generated.push_str(&token_list);

    let presentation_source =
        fs::read_to_string(manifest_dir.join("presentation/oracle_fingerprints.tsv"))
            .expect("read generated presentation fingerprints");
    generated.push_str(
        "/// Generated external Oracle compatibility metadata. No Oracle prose is embedded.\n\
         const EMBEDDED_PRESENTATION_FACES: &[(&str, &str, &str, &str, &str)] = &[\n",
    );
    for (line_number, line) in presentation_source.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<_> = line.split('\t').collect();
        assert_eq!(
            fields.len(),
            5,
            "presentation fingerprint line {} must have five tab-separated fields",
            line_number + 1
        );
        generated.push_str(&format!(
            "    ({:?}, {:?}, {:?}, {:?}, {:?}),\n",
            fields[0], fields[1], fields[2], fields[3], fields[4]
        ));
    }
    generated.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_cards.rs");
    fs::write(&out_path, generated).expect("write embedded_cards.rs");
}
