//! Generates the embedded card list from `data/**/*.ron` so adding a card never
//! requires editing source: drop a RON file in `data/` (any subdirectory) and it
//! is compiled in. Paths are sorted for deterministic output.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn collect_ron_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("read data dir") {
        let path = entry.expect("read data dir entry").path();
        if path.is_dir() {
            collect_ron_files(&path, out);
        } else if path.extension().is_some_and(|e| e == "ron") {
            out.push(path);
        }
    }
}

fn main() {
    // Directory-level: re-runs on file adds, removes, and edits anywhere under data/.
    println!("cargo:rerun-if-changed=data");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let mut files = Vec::new();
    collect_ron_files(&manifest_dir.join("data"), &mut files);
    files.sort();

    let mut generated = String::from(
        "/// Ron snippets compiled into the binary (hybrid model: data-first).\n\
         /// Generated by build.rs from `data/**/*.ron`; never edited by hand.\n\
         const EMBEDDED_RON_CHUNKS: &[&str] = &[\n",
    );
    for file in &files {
        let rel = file
            .strip_prefix(&manifest_dir)
            .expect("data file under manifest dir")
            .to_str()
            .expect("utf-8 path")
            .replace('\\', "/");
        generated.push_str(&format!(
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\")),\n"
        ));
    }
    generated.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_cards.rs");
    fs::write(&out_path, generated).expect("write embedded_cards.rs");
}
